### ISSUE TITLE
UnableToResolveError: Unable to resolve module `recyclerlistview`

### ISSUE THREAD

**Issue by SudoPlz** [Flipkart/recyclerlistview#100]
I receive that error when building from master (because I want version 1.2.6 which is not yet published on npm), any idea why?

```
error: bundling failed: UnableToResolveError: Unable to resolve module `recyclerlistview` from `/Users/io/Development/demoProj/mobile/src/components/Shared/MiniCal/MiniCalendarManager.js`: Module does not exist in the module map or in these directories:
  /Users/io/Development/demoProj/mobile/node_modules

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
    at ModuleResolver.resolveNodeDependency (/Users/io/Development/demoProj/mobile/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:292:11)
    at ModuleResolution.tryResolveSync (/Users/io/Development/demoProj/mobile/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:103:16)
    at Object.tryResolveSync (/Users/io/Development/demoProj/mobile/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:118:12)
    at ResolutionRequest.resolveDependency (/Users/io/Development/demoProj/mobile/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:100:39)
    at dependencyNames.map.name (/Users/io/Development/demoProj/mobile/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:134:10)
    at Array.map (<anonymous>)
    at ResolutionRequest.resolveModuleDependencies (/Users/io/Development/demoProj/mobile/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:133:42)
    at module.readFresh.then (/Users/io/Development/demoProj/mobile/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:181:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

Any idea why?

Thanks!

**Comment by naqvitalha** [comment]
1.2.6 was in beta.. was merged yesterday. To build from source run the build script since the source is in TypeScript. You'll need TypeScript, file-directives and TSLint present on your system.

**Comment by naqvitalha** [comment]
1.2.6 was in beta.. was merged yesterday. To build from source run the build script since the source is in TypeScript. You'll need TypeScript, file-directives and TSLint present on your system.

**Comment by SudoPlz** [comment]
Got it, thanks for letting me know :)
